/**
 * Content-Security-Policy-Report-Only, per §24.7's "no policy is written" —
 * with the enforcement question left to §9, this gathers real violations
 * from real browsers without breaking anything (TOLERANCE 0: nothing here
 * can change what a page executes).
 *
 * The draft policy is the enforcing policy §9 would eventually want, with
 * the two documented concessions from §24 built in:
 *  - 'unsafe-eval' on script-src for /app: the vendored Alpine standard
 *    build evaluates x- expressions through the AsyncFunction constructor
 *    (§24.3, copied out of the minified file) — genuinely required by the
 *    vendored build, NOT the CDN variant; the CSP build exists precisely to
 *    drop it.
 *  - 'unsafe-inline' on style-src: 23 of 24 public pages carry inline
 *    <style> (§24.5/§24.6).
 * Violations against this draft are the evidence §9 needs to tighten it.
 *
 * Report-Only means the browser applies nothing: every page behaves exactly
 * as today, and each violation POSTs to /api/csp-report for collection.
 */
import { Hono } from 'hono'
import type { AppEnv } from '../types.js'
import { randomUUID } from 'node:crypto'

export const CSP_REPORT_PATH = '/api/csp-report'

/**
 * The draft policy. Kept here rather than inlined at each mount so the
 * header and the recorded rationale cannot drift apart.
 */
export function draftCsp(): string {
  return [
    "default-src 'self'",
    // 'unsafe-eval' for the vendored Alpine's AsyncFunction evaluator
    // (§24.3); googletagmanager for GA4 and cdnjs for GSAP on the public
    // pages (§24.6). 'unsafe-inline' on script-src covers the 51 executable
    // inline blocks and the 54 handler attributes on the frozen pages —
    // report-only, so the report will show exactly how much.
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://cdnjs.cloudflare.com",
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com",
    "img-src 'self' data:",
    "connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com",
    "frame-ancestors 'self'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join('; ')
}

/** Mounts the Report-Only header on every response. */
export function cspReportOnly() {
  return async function cspReportOnly(_c: unknown, next: () => Promise<void>) {
    await next()
    const c = _c as { header: (k: string, v: string) => void }
    c.header('Content-Security-Policy-Report-Only', draftCsp())
  }
}

/**
 * The collector. The browser POSTs a JSON violation report (CSP level 3
 * shape: { "csp-report": {...} } for the report-uri form). Unauthenticated
 * by design — a violation report is generated by the browser, not by a
 * session, and requiring one would lose every violation on a logged-out
 * public page. It writes nothing to the database: reports land in the
 * server log in a greppable shape, and the endpoint answers 204 so the
 * browser does not retry.
 */
export const cspReportRoutes = new Hono<AppEnv>()

cspReportRoutes.post('/api/csp-report', async (c) => {
  const body = await c.req.text()
  // Greppable one-line shape: TS:CO csp-violation {...}
  console.log(`TS:CO csp-violation ${body.slice(0, 4000)}`)
  return c.body(null, 204)
})

/** A marker for tests: the header value the middleware stamps. */
export function cspReportHeaderName(): string {
  return 'content-security-policy-report-only'
}

export { randomUUID }
