-- 008_crm.sql
-- Spec 6.7: leads, activities, stage history, site visits, quotes and
-- competitors.
--
-- The pipeline stages and the site-visit fields are taken verbatim from the
-- spec, because they encode how a construction sale actually closes: the
-- qualifier is clear title and a sanctionable plan, not interest level.
--
-- leads.enquiry_id is UNIQUE and nullable, so a website enquiry becomes at
-- most one lead and a phone or walk-in lead needs no enquiry row.

CREATE TABLE competitors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  notes TEXT NULL,
  typical_rate_per_sqft_paise BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_competitor_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE leads (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lead_no VARCHAR(24) NOT NULL,
  enquiry_id BIGINT UNSIGNED NULL,
  client_id BIGINT UNSIGNED NULL,
  contact_name VARCHAR(140) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  alt_phone VARCHAR(20) NULL,
  email VARCHAR(190) NULL,
  lead_source_id BIGINT UNSIGNED NULL,
  campaign_id BIGINT UNSIGNED NULL,
  referred_by_client_id BIGINT UNSIGNED NULL,
  enquiry_type ENUM('residential_construction','commercial_construction',
    'industrial_construction','interior_fitout','renovation',
    'equipment_rental','consultation_only') NOT NULL DEFAULT 'residential_construction',
  site_city VARCHAR(80) NULL,
  site_locality VARCHAR(120) NULL,
  survey_number VARCHAR(60) NULL,
  plot_area_sqft DECIMAL(12,2) NULL,
  plot_dimensions VARCHAR(40) NULL,
  target_built_up_sqft DECIMAL(12,2) NULL,
  floors_wanted TINYINT UNSIGNED NULL,
  jurisdiction ENUM('BBMP','BMRDA','BDA','Gram Panchayat','TUDA','KIADB','Other') NULL,
  plot_ownership ENUM('owned_clear_title','owned_under_verification','agreement_stage',
    'joint_development','not_yet_purchased') NULL,
  has_sanctioned_plan TINYINT(1) NULL,
  has_architect TINYINT(1) NULL,
  architect_name VARCHAR(140) NULL,
  budget_min_paise BIGINT NULL,
  budget_max_paise BIGINT NULL,
  preferred_package_id BIGINT UNSIGNED NULL,
  funding_mode ENUM('self','home_loan','loan_sanctioned','loan_applied','company_capex') NULL,
  expected_start ENUM('immediate','within_1_month','1_to_3_months',
    '3_to_6_months','beyond_6_months','exploring') NULL,
  stage ENUM('new','contacted','qualified','site_visit_scheduled','site_visit_done',
    'estimate_shared','quote_sent','negotiation','verbal_agreement',
    'won','lost','dormant','disqualified') NOT NULL DEFAULT 'new',
  stage_changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  score TINYINT UNSIGNED NOT NULL DEFAULT 0,
  temperature ENUM('hot','warm','cold') NOT NULL DEFAULT 'warm',
  assigned_to BIGINT UNSIGNED NULL,            -- NULL is the unassigned pool
  assigned_at DATETIME NULL,
  next_action VARCHAR(200) NULL,
  next_action_date DATE NULL,
  first_response_at DATETIME NULL,
  expected_value_paise BIGINT NULL,
  probability_pct TINYINT UNSIGNED NULL,
  lost_reason ENUM('price','timeline','competitor','plot_issue','loan_rejected',
    'postponed','no_response','out_of_scope','duplicate','other') NULL,
  lost_to_competitor VARCHAR(140) NULL,
  lost_notes VARCHAR(500) NULL,
  converted_project_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_lead_no (lead_no),
  UNIQUE KEY uq_lead_enquiry (enquiry_id),
  KEY idx_leads_stage (stage),
  KEY idx_leads_assigned (assigned_to, stage),
  KEY idx_leads_next (next_action_date),
  CONSTRAINT fk_lead_enquiry FOREIGN KEY (enquiry_id) REFERENCES enquiries (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_source FOREIGN KEY (lead_source_id) REFERENCES lead_sources (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_referrer FOREIGN KEY (referred_by_client_id) REFERENCES clients (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_package FOREIGN KEY (preferred_package_id) REFERENCES site_packages (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_assignee FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_project FOREIGN KEY (converted_project_id) REFERENCES projects (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_lead_updated FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lead_activities (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lead_id BIGINT UNSIGNED NOT NULL,
  activity_type ENUM('call_out','call_in','whatsapp','email','meeting',
    'site_visit','quote_sent','follow_up','note','status_change') NOT NULL,
  occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  duration_minutes SMALLINT UNSIGNED NULL,
  outcome ENUM('connected','no_answer','busy','wrong_number','call_back_later',
    'not_interested','positive','negative','neutral') NULL,
  summary VARCHAR(500) NOT NULL,
  next_action VARCHAR(200) NULL,
  next_action_date DATE NULL,
  file_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_act_lead (lead_id, occurred_at),
  CONSTRAINT fk_act_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE,
  CONSTRAINT fk_act_file FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE RESTRICT,
  CONSTRAINT fk_act_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lead_stage_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lead_id BIGINT UNSIGNED NOT NULL,
  from_stage VARCHAR(30) NULL,
  to_stage VARCHAR(30) NOT NULL,
  changed_by BIGINT UNSIGNED NOT NULL,
  changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  days_in_previous_stage SMALLINT UNSIGNED NULL,
  note VARCHAR(300) NULL,
  KEY idx_lsh_lead (lead_id, changed_at),
  CONSTRAINT fk_lsh_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE,
  CONSTRAINT fk_lsh_user FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE site_visits (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lead_id BIGINT UNSIGNED NOT NULL,
  scheduled_at DATETIME NOT NULL,
  visited_at DATETIME NULL,
  visited_by BIGINT UNSIGNED NULL,
  status ENUM('scheduled','completed','client_no_show','rescheduled','cancelled')
    NOT NULL DEFAULT 'scheduled',
  soil_type VARCHAR(80) NULL,
  road_access ENUM('good','narrow','no_access') NULL,
  water_availability ENUM('borewell','corporation','tanker','none') NULL,
  power_availability TINYINT(1) NULL,
  neighbouring_structures TEXT NULL,
  level_difference_ft DECIMAL(5,2) NULL,
  demolition_required TINYINT(1) NULL,
  tree_cutting_permission_needed TINYINT(1) NULL,
  access_constraints TEXT NULL,
  feasibility ENUM('feasible','feasible_with_conditions','not_feasible') NULL,
  conditions_notes TEXT NULL,
  estimated_extra_cost_paise BIGINT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_visit_lead (lead_id),
  CONSTRAINT fk_visit_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE,
  CONSTRAINT fk_visit_user FOREIGN KEY (visited_by) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_visit_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quotes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  quote_no VARCHAR(24) NOT NULL,
  revision TINYINT UNSIGNED NOT NULL DEFAULT 1,
  lead_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NULL,
  quote_date DATE NOT NULL,
  valid_until DATE NOT NULL,
  pricing_basis ENUM('per_sqft','item_rate','lumpsum') NOT NULL DEFAULT 'per_sqft',
  built_up_area_sqft DECIMAL(12,2) NULL,
  rate_per_sqft_paise BIGINT NULL,
  base_amount_paise BIGINT NOT NULL DEFAULT 0,
  extras_amount_paise BIGINT NOT NULL DEFAULT 0,
  discount_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
  discount_amount_paise BIGINT NOT NULL DEFAULT 0,
  discount_approved_by BIGINT UNSIGNED NULL,
  subtotal_paise BIGINT NOT NULL DEFAULT 0,
  gst_pct DECIMAL(5,2) NOT NULL DEFAULT 18.00,
  gst_paise BIGINT NOT NULL DEFAULT 0,
  total_paise BIGINT NOT NULL DEFAULT 0,
  exclusions TEXT NULL,
  payment_schedule_json JSON NULL,
  status ENUM('draft','pending_approval','approved','sent','viewed',
    'accepted','rejected','expired','superseded') NOT NULL DEFAULT 'draft',
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  sent_at DATETIME NULL,
  accepted_at DATETIME NULL,
  rejected_reason VARCHAR(300) NULL,
  supersedes_quote_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_quote_no_rev (quote_no, revision),
  KEY idx_quotes_lead (lead_id, revision),
  KEY idx_quotes_status (status),
  CONSTRAINT fk_quote_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE,
  CONSTRAINT fk_quote_package FOREIGN KEY (package_id) REFERENCES site_packages (id) ON DELETE RESTRICT,
  CONSTRAINT fk_quote_discount_approver FOREIGN KEY (discount_approved_by) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_quote_approver FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_quote_supersedes FOREIGN KEY (supersedes_quote_id) REFERENCES quotes (id) ON DELETE SET NULL,
  CONSTRAINT fk_quote_created FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quote_lines (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  quote_id BIGINT UNSIGNED NOT NULL,
  line_type ENUM('package','addon','exclusion_note','extra_work','discount') NOT NULL DEFAULT 'addon',
  description VARCHAR(300) NOT NULL,
  qty DECIMAL(14,3) NULL,
  unit_id BIGINT UNSIGNED NULL,
  rate_paise BIGINT NULL,
  amount_paise BIGINT NOT NULL DEFAULT 0,
  cost_head_id BIGINT UNSIGNED NULL,
  sort_order SMALLINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ql (quote_id, sort_order),
  CONSTRAINT fk_ql_quote FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE,
  CONSTRAINT fk_ql_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE RESTRICT,
  CONSTRAINT fk_ql_cost_head FOREIGN KEY (cost_head_id) REFERENCES cost_heads (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
